-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 09:41:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cadastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cadastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastro` DEFAULT CHARACTER SET utf8 ;
USE `cadastro` ;

-- -----------------------------------------------------
-- Table `cadastro`.`coordenadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`coordenadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `unidade_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcoordenadores_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_coordenadores_unidades_idx` (`unidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_coordenadores_unidades`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `cadastro`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`unidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `localização` MEDIUMTEXT NULL,
  `coordenadora_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_unidades_coordenadores1_idx` (`coordenadora_id` ASC) VISIBLE,
  CONSTRAINT `fk_unidades_coordenadores1`
    FOREIGN KEY (`coordenadora_id`)
    REFERENCES `cadastro`.`coordenadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `nascimento` DATE NULL,
  `email` VARCHAR(255) NOT NULL,
  `unidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_alunos_unidades1_idx` (`unidade_id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_unidades1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `cadastro`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`professores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `materia` ENUM("Humanas", "Exatas") NULL,
  `unidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idprofessores_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_professores_unidades1_idx` (`unidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_professores_unidades1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `cadastro`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro`.`boletins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`boletins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aluno_id` INT NOT NULL,
  `notas` JSON NULL,
  `etapa` TINYINT NULL,
  `ano` YEAR NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_boletins_alunos1_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_boletins_alunos1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `cadastro`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro`.`prova_solicitação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`prova_solicitação` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aluno_id` INT NOT NULL,
  `unidade_id` INT NOT NULL,
  `data_requisitado` DATE NULL,
  `data_prova` DATE NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prova_solicitação_alunos1_idx` (`aluno_id` ASC) VISIBLE,
  INDEX `fk_prova_solicitação_unidades1_idx` (`unidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_prova_solicitação_alunos1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `cadastro`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prova_solicitação_unidades1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `cadastro`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `cadastro` ;

-- -----------------------------------------------------
-- Placeholder table for view `cadastro`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `cadastro`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastro`.`view1`;
USE `cadastro`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
